---
homebrew:
  - dog # dig alternative
  - pgcli # psql alternative
  - dust # du alternative
  - diff-so-fancy # diff interpreter
  - pyenv
  - wader/tap/fq # binary parser
  - mdcat # markdown reader
  - clipboard # clipboard manager
  - rust # + cargo package manager
  - watchexec # file watcher
  - qrencode # qrcode creator
